version: "3"
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: "0:0"
    container_name: sqlserver2019
    ports:
      - 1433:1433
    expose:
      - 1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: "Appladupla21"
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql
    networks:
      - ladupla
  fastapi:
    build:
      context: .
      dockerfile: "./Dockerfile"
    ports:
      - "5000:5000"
    networks:
      - ladupla
    depends_on:
      - db

networks:
  ladupla:
